### ISSUE TITLE
nw_connection_get_connected_socket 42 Connection has no connected handler

### ISSUE THREAD

**Issue by rangav** [pentarex/react-native-gallery-manager#1]
Hi

Thanks for creating this library. 

I am getting this error: 
`nw_connection_get_connected_socket 42 Connection has no connected handler `
when i run on Device. It works fine on simulator.

Device:
iPad (OS 10.3.3): The above error is displayed and cannot get any photos.

iPhone (OS 11.2.2). The above is displayed, but getting the photos.

There is similar issue in RN
https://github.com/facebook/react-native/issues/10027

**Comment by pentarex** [comment]
Hi, thanks for the issue.

I am not sure if this comes from the library. 
I had it also before and the solution is mentioned [here](https://github.com/facebook/react-native/issues/10027#issuecomment-249338419)

And also if interested, I just pushed a new version (1.0.0) which adds android support and please check the response structure, Ive removed "asset" from the response.

If the solution mentioned above doesn't work please let me know :)

**Comment by rangav** [comment]
Thanks for your reply that fixed the issue.

currently i am using this library for iOS app only.

Happy to contribute if you need any assistance in managing this library.
