### ISSUE TITLE
NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects

### ISSUE THREAD

**Issue by rangav** [pentarex/react-native-gallery-manager#2]
Hi

Got the below error when trying to run on iPad device with OS 10.3.3

`'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects`

I debugged the code and found that its failing when mimeType is null (when image is HEIC type the mimeType is null).

```
   [assets addObject:@{
                        @"type": [self getMediaType:([asset mediaType])],
                        @"width": @([asset pixelWidth]),
                        @"height": @([asset pixelHeight]),
                        @"filename": orgFilename ?: @"",
                        @"mimeType": mimeType,
                        @"id": [asset localIdentifier],
                        @"creationDate": [asset creationDate],
                        @"uri": [self buildAssetUri:[asset localIdentifier] extension:extension],
                        @"duration": @([asset duration])
                        }];
  }];

```
So the fix is to supply default when its null.
`@"mimeType": mimeType ?: @""`

**Comment by pentarex** [comment]
Thanks, I will fix it in a while and push :)

**Comment by pentarex** [comment]
1.0.1 out :) try to see if this happens again, also I've fixed another issue where resources is empty and it was throwing exception. 
Please let me know if 1.0.1 fixed the mime type so I can close it

**Comment by rangav** [comment]
i saw you added 

```
NSArray *resources = [PHAssetResource assetResourcesForAsset:asset ];
    if ([resources count] < 1) return;
```
i think we should use continue keyword, for skipping only current asset loop.

```
NSArray *resources = [PHAssetResource assetResourcesForAsset:asset ];
    if ([resources count] < 1) continue;
```

**Comment by pentarex** [comment]
yeah, in enumerateObjects there is no continue, return with stop = NO: is continue, if return and stop = YES; is used then its stopping the loop. 

I am closing this issue, I guess there is no issue here anymore. Feel free to reopen it
