### ISSUE TITLE
Compress Video and Image for Android

### ISSUE THREAD

**Issue by rangav** [pentarex/react-native-gallery-manager#28]
Hi @pentarex This is library was very useful for me on iOS, now developing Android.

Do you know how compress video and Image on Android. i was able to do it on iOS.

Any code sample would appreciate.

**Comment by gbferreira** [comment]
I know one library to compress videos in Android and IOS:  https://www.npmjs.com/package/react-native-video-helper

**Comment by rangav** [comment]
Yes looks good.
