### ISSUE TITLE
GetAssets func sort order is not consistent

### ISSUE THREAD

**Issue by rangav** [pentarex/react-native-gallery-manager#4]
Hi @pentarex 

Had another issue with sorting of images.
use of `NSEnumerationConcurrent` in below line is not maintaining proper descending order of creation date.

is there a way to keep it consistent.

` [fetchResults enumerateObjectsAtIndexes:indexSet options:NSEnumerationConcurrent usingBlock:^(PHAsset * _Nonnull asset, NSUInteger index, BOOL * _Nonnull stop) {`

**Comment by rangav** [comment]
Actually found a solution

We should replace the below line

`[fetchResults enumerateObjectsAtIndexes:indexSet options:NSEnumerationConcurrent usingBlock:^(PHAsset * _Nonnull asset, NSUInteger index, BOOL * _Nonnull stop) `

with

```
NSArray<PHAsset*>  *results = [fetchResults objectsAtIndexes:indexSet];
  
for (PHAsset* asset in results) {
....
}
```

This will keep results in proper sort order by creation date (desc order).

**Comment by rangav** [comment]
and also no need for this check i think
```
// Check if the requested limit is reached
     if (limit - 1 == index) {
        *stop = YES; // stop the iteration
     }
```
as indexSet will get results by limit exactly.

**Comment by pentarex** [comment]
thank you for the contribution man. 👍 lets make react-native gallery great again :D

**Comment by pentarex** [comment]
you can update 1.0.2

**Comment by rangav** [comment]
Sure man 👍 this package is good starting point to build a great camera roll library that is useful for RN developers.
